python val_score.py output/VANILLA_3D_CONV_RESNEXT_LABEL_WEIGHTS_UNION_FEAT/all_results_vidor_checkpoint_epoch_00004.pyth_proposal_less-168-examples.json
python val_score.py output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT/all_results_vidor_checkpoint_epoch_00004.pyth_proposal_less-168-examples.json
python val_score.py output/VANILLA_3D_CONV_RESNEXT_DROPOUT_UNION_FEAT_FOCAL_LOSS/all_results_vidor_checkpoint_epoch_00010.pyth_proposal_less-168-examples.json 
python val_score.py output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_PROPENSITY/all_results_vidor_checkpoint_epoch_00006.pyth_proposal_less-168-examples.json
python val_score.py output/SLOWFAST_32x2_R50_SHORT_SCRATCH_EVAL_GT_trajectory-toipool/all_results_vidor_checkpoint_epoch_00020.pyth_proposal_less-168-examples.json 


#python val_score.py output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_DETECTION/all_results_vidor_checkpoint_epoch_00004.pyth_proposal_less-168-examples.json

#python val_score.py output/VANILLA_3D_CONV_RESNEXT_LABEL_WEIGHTS_UNION_FEAT_DETECTION/all_results_vidor_checkpoint_epoch_00004.pyth_proposal_less-168-examples.json

#python val_score.py output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_COORD_MASK_DETECTION/all_results_vidor_checkpoint_epoch_00004.pyth_proposal_less-168-examples.json

#python val_score.py output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_COORD_MASK_POSE_DETECTION/all_results_vidor_checkpoint_epoch_00004.pyth_proposal_less-168-examples.json
