# to generate results for detection
# used input as image, change predicted box list to det_val_frames...
# have set use_saved_feat false and use_trajectories true in config file
# TODO: Select appropriate checkpoint for each setting

##################
# Remove this later - used GT boxes not detected
##################

# to validate vanilla BCE with weights for images
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_LABEL_WEIGHTS_UNION_FEAT/checkpoints/checkpoint_epoch_00004.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True DEMO.ENABLE_ALL True MODEL.USE_SAVED_FEAT False MODEL.USE_TRAJECTORIES True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_LABEL_WEIGHTS_UNION_FEAT

# to validate vanilla BCE w/o weights
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT/checkpoints/checkpoint_epoch_00004.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True MODEL.USE_SAVED_FEAT False MODEL.USE_TRAJECTORIES True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT

# to validate vanilla focal_loss with weights
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_DROPOUT_UNION_FEAT_FOCAL_LOSS/checkpoints/checkpoint_epoch_00010.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True MODEL.USE_FOCAL_LOSS True MODEL.USE_SAVED_FEAT False MODEL.USE_TRAJECTORIES True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_DROPOUT_UNION_FEAT_FOCAL_LOSS

# to validate vanilla BCE with weights + pose
CUDA_VISIBLE_DEVICES=3 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_POSE/checkpoints/checkpoint_epoch_00003.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True MODEL.USE_ALPHA_POSES True MODEL.USE_SAVED_FEAT False MODEL.USE_TRAJECTORIES True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_POSE

#################
# For Detection

# to validate basline
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/SLOWFAST_32x2_R50_SHORT_SCRATCH_EVAL_NONGT_trajectory-toipool.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./checkpoints/SLOWFAST_32x2_R50_SHORT_SCRATCH_EVAL_GT_trajectory-toipool/checkpoint_epoch_00020.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False

# to validate vanilla BCE w/o weights
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT_DETECTION.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT/checkpoints/checkpoint_epoch_00004.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_DETECTION

# to validate vanilla BCE with weights
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT_DETECTION.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_LABEL_WEIGHTS_UNION_FEAT/checkpoints/checkpoint_epoch_00004.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_LABEL_WEIGHTS_UNION_FEAT_DETECTION

# to validate vanilla BCE with weights + coord_mask
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT_DETECTION.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_COORD_MASK/checkpoints/checkpoint_epoch_00004.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True MODEL.USE_COORD_MASK True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_COORD_MASK_DETECTION

# to validate vanilla BCE with weights + coord_mask + pose
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT_DETECTION.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_COORD_MASK_POSE/checkpoints/checkpoint_epoch_00004.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True MODEL.USE_COORD_MASK True MODEL.USE_ALPHA_POSES True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_COORD_MASK_POSE_DETECTION 

# to validate vanilla BCE with weights + pose
#CUDA_VISIBLE_DEVICES=2 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT_DETECTION.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_POSE/checkpoints/checkpoint_epoch_00003.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True MODEL.USE_ALPHA_POSES True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_POSE_DETECTION

# to validate vanilla focal_loss with weights
#CUDA_VISIBLE_DEVICES=3 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT_DETECTION.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_DROPOUT_UNION_FEAT_FOCAL_LOSS/checkpoints/checkpoint_epoch_00010.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True MODEL.USE_FOCAL_LOSS True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_DROPOUT_UNION_FEAT_FOCAL_LOSS_DETECTION

# to validate vanilla propensity
#CUDA_VISIBLE_DEVICES=1 python tools/run_net_vidor.py --cfg configs/vidor/VANILLA_TRAIN_RESNEXT101_FEAT_DETECTION.yaml DATA.PATH_TO_DATA_DIR slowfast/datasets/vidor NUM_GPUS 1 DATA_LOADER.NUM_WORKERS 0 TEST.BATCH_SIZE 1 LOG_MODEL_INFO False TRAIN.ENABLE False TEST.CHECKPOINT_FILE_PATH ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_PROPENSITY/checkpoints/checkpoint_epoch_00006.pyth TRAIN.CHECKPOINT_TYPE pytorch VIDOR.TEST_DEBUG False MODEL.USE_UNION_BBOX True MODEL.USE_3D_CONV True MODEL.USE_PROPENSITY True OUTPUT_DIR ./output/VANILLA_3D_CONV_RESNEXT_UNION_FEAT_PROPENSITY_DETECTION
